audio_parameters:
  segment_length: 25400
  sample_rate: 22050
  hop_length: 200
  window_length: 800
  n_mels: 128
  mean: -37.334929861258004
  standard_deviation: 17.89131129988776
  global_min: -2.50209641456604
  global_max: 3.608585834503174
unet_training:
  spectrogram_files_directory: C:/Users/snk/Documents/REPOS/mel-steg-cINN/Testy/Output
  batch_checkpoint: 1
  parameters:
    add_noise: False
    batch_size: 5
    learning_rate: 0.01
    momentum: 0.9
    epochs: 5