audio_parameters:

    # 512x512
    segment_length: 102200
    sample_rate: 22050
    hop_length: 200
    window_length: 2048
    n_mels: 512
    mean: -29.76158387351581
    standard_deviation: 16.546569945047125
    global_min: -1.3392828702926636
    global_max: 3.1347999572753906

    # # 256x256
    # segment_length: 51000
    # sample_rate: 22050
    # hop_length: 200
    # window_length: 1024
    # n_mels: 256
    # mean: -35.93647618796097
    # standard_deviation: 17.02300907660197
    # global_min: -1.9601174592971802
    # global_max: 2.7394044399261475

    # # 128x128
    # segment_length: 25400
    # sample_rate: 22050
    # hop_length: 200
    # window_length: 800
    # n_mels: 128
    # mean: -37.36893585525392
    # standard_deviation: 17.880760586984575
    # global_min: -2.3468124866485596
    # global_max: 2.127270221710205

unet_training:    
    global_parameters:
        spectrogram_files_directory: /storage/data/spectrograms_6000
        batch_checkpoint: 5
        add_noise: True
        noise_mean: [0.0]
        noise_variance: [0.001, 0.001, 0.0]
        dataset_size: 1000 #If null then whole dataset is taken
        sweep_count: 50
    sweep_config:        
        method: 'grid'
        metric: 
            goal: 'minimize'
            name: 'VALID_AVG_Loss'
        parameters: 
            batch_size: 
                value: 10
            epochs: 
                value: 5
            lr: 
                values: [0.1, 0.05, 0.01, 0.005, 0.001, 0.00075, 0.0005, 0.00025, 0.0001, 0.000075, 0.00005, 0.000025, 0.00001]
                # distribution: 'uniform'
                # max: 1e-2
                # min: 1e-5
            enable_lr_scheduler:
                value: False
            loss_function:
                value: "HuberLoss"
            model:
                values: ["custom_unet", "unet"]
    regular_config:
        batch_size: 10
        epochs: 5
        lr: 0.001
        enable_lr_scheduler: False
        loss_function: "MSELoss"
        model: "unet"