audio_parameters:
    segment_length: 25400
    sample_rate: 22050
    hop_length: 200
    window_length: 800
    n_mels: 128
    mean: -37.334929861258004
    standard_deviation: 17.89131129988776
    global_min: -2.50209641456604
    global_max: 3.608585834503174
unet_training:    
    global_parameters:
        spectrogram_files_directory: /notebooks/Output
        batch_checkpoint: 3
        add_noise: False
        batch_size: 3
        learning_rate: 0.01
        epochs: 250
        dataset_size: 10 #If null then whole dataset is taken
        sweep_count: 50
    sweep_config:        
        method: 'grid'
        metric: 
            goal: 'minimize'
            name: 'TRAIN_AVG_Loss'
        parameters: 
            batch_size: 
                value: 3
            epochs: 
                value: 10
            lr: 
                values: [0.1, 0.01, 0.001, 0.00075, 0.0005, 0.00025, 0.0001, 0.000075, 0.00005, 0.000025, 0.00001]
                #distribution: 'uniform'
                #max: 7e-3
                #min: 7e-4
            enable_lr_scheduler:
                value: False
            loss_function:
                values: ["HuberLoss", "MSELoss"]
    regular_config:
        batch_size: 3
        epochs: 100
        lr: 0.01
        enable_lr_scheduler: False
        loss_function: "MSELoss"