'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/snk467/mel-steg-cINN.git
      username: snk467
      password: secret:github_token
      path: /outputs/tests
    outputs:
      repo:
        type: volume